"""
AI summarization for Medical Daily Digest via OpenAI-compatible API.
"""

import os
import requests


SYSTEM_PROMPT = """你是一位专注于医疗健康领域的 AI 资讯编辑，拥有医学背景，熟悉医疗 AI、数字健康、生物科技和制药行业。

你的任务是将收集到的原始医疗健康资讯整理成一份高质量的每日简报，目标读者是医疗 AI 研究者、临床医生、数字健康从业者和医疗科技投资人。

要求：
1. 从提供的原始内容中筛选出最有价值的 10-15 条资讯
2. 去除重复、低质量或与医疗/健康/生物技术无关的内容
3. 按类别分组：
   - 📰 行业动态（产品发布、公司新闻、监管政策）
   - 🔬 临床研究（临床试验、研究结果、医学进展）
   - 🤖 医疗 AI（AI 算法、医疗大模型、智能诊断、影像 AI）
   - 💊 生物医药（新药、疗法、FDA 审批）
4. 每条资讯格式如下：
   - **标题**：一句话摘要。
     - 重要性：★★★★☆ / 5
     - 为什么重要：对临床实践、医疗产业或患者的影响。
     - 来源：[Source Name](URL)
5. 在末尾加一段"今日洞察"（3-5 句话），从医疗 AI 视角点评今天的整体趋势
6. 所有内容必须基于提供的原始素材，不要编造
7. 输出格式为 Markdown，中英文混排，专有名词、药名、模型名保留英文
"""


def format_raw_content(data: dict) -> str:
    sections = []

    if data.get("news"):
        sections.append("=== 行业新闻 ===")
        for item in data["news"]:
            sections.append(
                f"[{item['source']}] {item['title']}\n"
                f"URL: {item['url']}\n"
                f"Published: {item.get('published') or 'unknown'}\n"
                f"Importance hint: {item.get('importance_hint', 3)}/5\n"
                f"{item['summary']}\n"
            )

    if data.get("papers"):
        sections.append("=== 学术论文 ===")
        for item in data["papers"]:
            sections.append(
                f"[{item['source']}] {item['title']}\n"
                f"URL: {item['url']}\n"
                f"Importance hint: {item.get('importance_hint', 3)}/5\n"
                f"{item['summary']}\n"
            )

    return "\n".join(sections)


def summarize(data: dict, date_str: str) -> str:
    api_key = os.environ.get("API_KEY")
    if not api_key:
        raise ValueError("API_KEY environment variable is required")

    base_url = os.environ.get("API_BASE_URL", "https://api.deepseek.com")
    model = os.environ.get("API_MODEL", "deepseek-chat")

    raw_content = format_raw_content(data)
    if not raw_content.strip():
        return f"# Medical AI Daily - {date_str}\n\n> No content fetched today.\n"

    user_prompt = f"""今天是 {date_str}。

以下是今天收集到的医疗健康领域原始资讯，请整理成每日简报。
优先选择：有临床意义、有 FDA/监管进展、医疗 AI 实际落地、重要融资/并购的内容。

{raw_content}"""

    url = f"{base_url}/chat/completions"
    headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": 0.7,
        "max_tokens": 4096,
    }

    print(f"Calling {model}...")
    resp = requests.post(url, headers=headers, json=payload, timeout=120)
    resp.raise_for_status()

    text = resp.json()["choices"][0]["message"]["content"]
    return f"# Medical AI Daily - {date_str}\n\n{text}\n\n---\n*Generated by Medical AI Daily using {model}*\n"
